[package]
name = "bitdecode-rs"
version = "0.1.0"
authors = ["TE-KazuhiroYabe <Kazuhiro.Yabe@sony.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
bitcode_uint_is_u128 = []

